drop table if exists user CASCADE;
create table user
(
    id bigint generated by default as identity,
    name varchar(255),
    password varchar(255),
    primary key (id)
)
drop table if exists design CASCADE;
create table design
(
    id bigint generated by default as identity,
    user_name varchar(255),
    file_route varchar(255),
    price int,
    primary key (id)
)